[package]
name = "iratxo-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
iratxo-core = { path = "../crates/iratxo-core" }
libfuzzer-sys = "0.4"

[[bin]]
name = "interpret"
path = "fuzz_targets/interpret.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode"
path = "fuzz_targets/decode.rs"
test = false
doc = false
bench = false

[workspace]
