//! Verifies that our Basque stemmer produces the same output as marrow's
//! reference implementation for every word in `basque_golden.tsv`. The TSV
//! was generated by running marrow's stemmer over the inputs listed in its
//! own `stem_test.go`.

use iratxo_core::text::{stem, Language};

#[test]
fn matches_marrow_golden() {
    let tsv = include_str!("basque_golden.tsv");
    let mut total = 0;
    let mut mismatches = Vec::new();
    for line in tsv.lines() {
        if line.is_empty() { continue; }
        let mut parts = line.split('\t');
        let input = parts.next().unwrap();
        let expected = parts.next().unwrap();
        let got = stem(input, Language::Basque);
        total += 1;
        if got != expected {
            mismatches.push(format!("{input}: got {got:?}, want {expected:?}"));
        }
    }
    let pct = (total - mismatches.len()) as f64 / total as f64 * 100.0;
    eprintln!("Basque parity: {}/{} = {:.2}%", total - mismatches.len(), total, pct);
    if !mismatches.is_empty() {
        for m in mismatches.iter().take(20) { eprintln!("  {m}"); }
        if mismatches.len() > 20 {
            eprintln!("  ... and {} more", mismatches.len() - 20);
        }
        panic!("{} mismatches out of {}", mismatches.len(), total);
    }
}
