// End-to-end test through the Node host. Reads a precompiled .iratxo blob
// (generated by the Rust CLI; see test/fixtures.js) and asserts the verdict.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { load } from "../src/node.js";

const here = dirname(fileURLToPath(import.meta.url));
const ruleBlob = await readFile(join(here, "fixtures", "compliance.iratxo"));

test("clean input classifies as ok", async () => {
  const iratxo = await load();
  const r = iratxo.run(ruleBlob, "Hi there. This is not financial advice.");
  assert.equal(r.classification, "ok");
});

test("violating input classifies as blocked", async () => {
  const iratxo = await load();
  const r = iratxo.run(ruleBlob, "Sign up for a guaranteed refund. Our product is FDA approved.");
  assert.equal(r.classification, "blocked");
  assert.ok(r.triggered.length >= 2);
});

test("multiple runs are independent", async () => {
  const iratxo = await load();
  for (let i = 0; i < 5; i++) {
    const r = iratxo.run(ruleBlob, "Just a clean message. This is not financial advice.");
    assert.equal(r.classification, "ok");
  }
});
